In [12]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [13]:
df=pd.read_csv("csgo_round_snapshots.csv")

In [14]:
df.head()

time_left  ct_score  t_score       map  bomb_planted  ct_health  t_health  \
0     175.00       0.0      0.0  de_dust2         False      500.0     500.0   
1     156.03       0.0      0.0  de_dust2         False      500.0     500.0   
2      96.03       0.0      0.0  de_dust2         False      391.0     400.0   
3      76.03       0.0      0.0  de_dust2         False      391.0     400.0   
4     174.97       1.0      0.0  de_dust2         False      500.0     500.0   

   ct_armor  t_armor  ct_money  ...  t_grenade_flashbang  \
0       0.0      0.0    4000.0  ...                  0.0   
1     400.0    300.0     600.0  ...                  0.0   
2     294.0    200.0     750.0  ...                  0.0   
3     294.0    200.0     750.0  ...                  0.0   
4     192.0      0.0   18350.0  ...                  0.0   

   ct_grenade_smokegrenade  t_grenade_smokegrenade  \
0                      0.0                     0.0   
1                      0.0                     2.0   
2                      0.0                     2.0   
3                      0.0                     0.0   
4                      0.0                     0.0   

   ct_grenade_incendiarygrenade  t_grenade_incendiarygrenade  \
0                           0.0                          0.0   
1                           0.0                          0.0   
2                           0.0                          0.0   
3                           0.0                          0.0   
4                           0.0                          0.0   

   ct_grenade_molotovgrenade  t_grenade_molotovgrenade  \
0                        0.0                       0.0   
1                        0.0                       0.0   
2                        0.0                       0.0   
3                        0.0                       0.0   
4                        0.0                       0.0   

   ct_grenade_decoygrenade  t_grenade_decoygrenade  round_winner  
0                      0.0                     0.0            CT  
1                      0.0                     0.0            CT  
2                      0.0                     0.0            CT  
3                      0.0                     0.0            CT  
4                      0.0                     0.0            CT  

[5 rows x 97 columns]

In [15]:
df.shape

(122410, 97)

In [16]:
df.columns

Index(['time_left', 'ct_score', 't_score', 'map', 'bomb_planted', 'ct_health',
       't_health', 'ct_armor', 't_armor', 'ct_money', 't_money', 'ct_helmets',
       't_helmets', 'ct_defuse_kits', 'ct_players_alive', 't_players_alive',
       'ct_weapon_ak47', 't_weapon_ak47', 'ct_weapon_aug', 't_weapon_aug',
       'ct_weapon_awp', 't_weapon_awp', 'ct_weapon_bizon', 't_weapon_bizon',
       'ct_weapon_cz75auto', 't_weapon_cz75auto', 'ct_weapon_elite',
       't_weapon_elite', 'ct_weapon_famas', 't_weapon_famas',
       'ct_weapon_g3sg1', 't_weapon_g3sg1', 'ct_weapon_galilar',
       't_weapon_galilar', 'ct_weapon_glock', 't_weapon_glock',
       'ct_weapon_m249', 't_weapon_m249', 'ct_weapon_m4a1s', 't_weapon_m4a1s',
       'ct_weapon_m4a4', 't_weapon_m4a4', 'ct_weapon_mac10', 't_weapon_mac10',
       'ct_weapon_mag7', 't_weapon_mag7', 'ct_weapon_mp5sd', 't_weapon_mp5sd',
       'ct_weapon_mp7', 't_weapon_mp7', 'ct_weapon_mp9', 't_weapon_mp9',
       'ct_weapon_negev', 't_weapon_negev',

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122410 entries, 0 to 122409
Data columns (total 97 columns):
 #   Column                        Non-Null Count   Dtype  
---  ------                        --------------   -----  
 0   time_left                     122410 non-null  float64
 1   ct_score                      122410 non-null  float64
 2   t_score                       122410 non-null  float64
 3   map                           122410 non-null  object 
 4   bomb_planted                  122410 non-null  bool   
 5   ct_health                     122410 non-null  float64
 6   t_health                      122410 non-null  float64
 7   ct_armor                      122410 non-null  float64
 8   t_armor                       122410 non-null  float64
 9   ct_money                      122410 non-null  float64
 10  t_money                       122410 non-null  float64
 11  ct_helmets                    122410 non-null  float64
 12  t_helmets                     122410 non-nul

In [67]:
df.describe(include="all")

time_left       ct_score        t_score            map  \
count  122410.000000  122410.000000  122410.000000  122410.000000   
mean       97.886922       6.709239       6.780435       3.520170   
std        54.465238       4.790362       4.823543       1.929088   
min         0.010000       0.000000       0.000000       0.000000   
25%        54.920000       3.000000       3.000000       2.000000   
50%        94.910000       6.000000       6.000000       3.000000   
75%       166.917500      10.000000      10.000000       5.000000   
max       175.000000      32.000000      33.000000       7.000000   

        bomb_planted      ct_health       t_health       ct_armor  \
count  122410.000000  122410.000000  122410.000000  122410.000000   
mean        0.111788     412.106568     402.714500     314.142121   
std         0.315107     132.293290     139.919033     171.029736   
min         0.000000       0.000000       0.000000       0.000000   
25%         0.000000     350.000000     322.000000     194.000000   
50%         0.000000     500.000000     500.000000     377.000000   
75%         0.000000     500.000000     500.000000     486.000000   
max         1.000000     500.000000     600.000000     500.000000   

             t_armor       ct_money  ...  t_grenade_flashbang  \
count  122410.000000  122410.000000  ...        122410.000000   
mean      298.444670    9789.023773  ...             1.858100   
std       174.576545   11215.042286  ...             1.794473   
min         0.000000       0.000000  ...             0.000000   
25%       174.000000    1300.000000  ...             0.000000   
50%       334.000000    5500.000000  ...             1.000000   
75%       468.000000   14600.000000  ...             3.000000   
max       500.000000   80000.000000  ...             7.000000   

       ct_grenade_smokegrenade  t_grenade_smokegrenade  \
count            122410.000000           122410.000000   
mean                  1.540814                1.627146   
std                   1.737804                1.829147   
min                   0.000000                0.000000   
25%                   0.000000                0.000000   
50%                   1.000000                1.000000   
75%                   3.000000                3.000000   
max                   6.000000                9.000000   

       ct_grenade_incendiarygrenade  t_grenade_incendiarygrenade  \
count                 122410.000000                122410.000000   
mean                       1.001969                     0.019819   
std                        1.458084                     0.143933   
min                        0.000000                     0.000000   
25%                        0.000000                     0.000000   
50%                        0.000000                     0.000000   
75%                        2.000000                     0.000000   
max                        5.000000                     3.000000   

       ct_grenade_molotovgrenade  t_grenade_molotovgrenade  \
count              122410.000000             122410.000000   
mean                    0.048011                  1.352095   
std                     0.227669                  1.663246   
min                     0.000000                  0.000000   
25%                     0.000000                  0.000000   
50%                     0.000000                  1.000000   
75%                     0.000000                  2.000000   
max                     3.000000                  5.000000   

       ct_grenade_decoygrenade  t_grenade_decoygrenade   round_winner  
count            122410.000000           122410.000000  122410.000000  
mean                  0.027694                0.025750       0.509811  
std                   0.169531                0.164162       0.499906  
min                   0.000000                0.000000       0.000000  
25%                   0.000000                0.000000       0.000000  
50%                   0.000000                0.000000

In [66]:
# There are no null values present in the dataset
df.isnull().sum().sum()

0

In [20]:
df["map"].value_counts()

de_inferno     23811
de_dust2       22144
de_nuke        19025
de_mirage      18576
de_overpass    14081
de_train       13491
de_vertigo     11137
de_cache         145
Name: map, dtype: int64

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 122410 entries, 0 to 122409
Data columns (total 97 columns):
 #   Column                        Non-Null Count   Dtype  
---  ------                        --------------   -----  
 0   time_left                     122410 non-null  float64
 1   ct_score                      122410 non-null  float64
 2   t_score                       122410 non-null  float64
 3   map                           122410 non-null  object 
 4   bomb_planted                  122410 non-null  bool   
 5   ct_health                     122410 non-null  float64
 6   t_health                      122410 non-null  float64
 7   ct_armor                      122410 non-null  float64
 8   t_armor                       122410 non-null  float64
 9   ct_money                      122410 non-null  float64
 10  t_money                       122410 non-null  float64
 11  ct_helmets                    122410 non-null  float64
 12  t_helmets                     122410 non-nul

In [22]:
for i in df.columns:
  if (df[i].dtypes=="object") | (df[i].dtypes=="bool"):
    print("Columns which have categorical values",i)

Columns which have categorical values map
Columns which have categorical values bomb_planted
Columns which have categorical values round_winner


In [23]:
df["bomb_planted"].value_counts()

False    108726
True      13684
Name: bomb_planted, dtype: int64

In [24]:
df["map"].value_counts()

de_inferno     23811
de_dust2       22144
de_nuke        19025
de_mirage      18576
de_overpass    14081
de_train       13491
de_vertigo     11137
de_cache         145
Name: map, dtype: int64

In [25]:
df["round_winner"].value_counts()

T     62406
CT    60004
Name: round_winner, dtype: int64

In [26]:
# Converting categorical features into a integer column
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
df["bomb_planted"]=le.fit_transform(df["bomb_planted"])
df["map"]=le.fit_transform(df["map"])
df["round_winner"]=le.fit_transform(df["round_winner"])

In [27]:
X=df.drop(columns=["round_winner"])
y=df[["round_winner"]]

In [28]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [29]:
# Scaling the data
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [30]:
# Applying Linear Discriminant Analysis
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

In [70]:
#lda=LinearDiscriminantAnalysis(n_components=20)
#min(n_classes-1, no.of features)
lda=LinearDiscriminantAnalysis()

In [71]:
y.value_counts()

round_winner
1               62406
0               60004
dtype: int64

In [72]:
lda.fit(x_train,y_train)

C:\Users\Dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


LinearDiscriminantAnalysis()

In [73]:
lda.transform(x_test)

array([[ 0.42856578],
       [-0.45508317],
       [ 1.90504288],
       ...,
       [-2.56342161],
       [ 1.25933387],
       [-0.58969535]])

In [38]:
# Obtaining the LDA coefficients.This will give the importance scores associated with each feature.

In [39]:
lda_coefficients=np.exp(np.abs(lda.coef_))

In [40]:
lda_coefficients

array([[1.14051375, 1.02348232, 1.02361012, 1.08711166, 1.26443741,
        1.56896428, 1.42226149, 1.71174795, 1.72149378, 1.22695841,
        1.17629264, 1.02925519, 1.17393359, 1.01233178, 1.17701202,
        1.26888831, 1.21975251, 1.80580698, 1.22872837, 1.03124048,
        1.37208174, 1.26351299, 1.        , 1.00130014, 1.00099319,
        1.03406233, 1.01079854, 1.01589366, 1.1511331 , 1.0481572 ,
        1.        , 1.01891369, 1.04559279, 1.13912974, 1.02386319,
        1.01009894, 1.        , 1.        , 1.10758456, 1.051198  ,
        1.62280372, 1.10928011, 1.01408145, 1.11733322, 1.02306813,
        1.00594113, 1.01383628, 1.04016588, 1.00546389, 1.00296978,
        1.1231047 , 1.0350133 , 1.        , 1.00757676, 1.02090408,
        1.00405543, 1.0252188 , 1.01962772, 1.        , 1.00493109,
        1.        , 1.01827676, 1.00401758, 1.01179667, 1.24546089,
        1.71649302, 1.08595734, 1.01928052, 1.05378886, 1.0817296 ,
        1.0223457 , 1.00392739, 1.00787732, 1.06

In [41]:
lda_coefficients= lda_coefficients.flatten()

In [42]:
lda_coefficients

array([1.14051375, 1.02348232, 1.02361012, 1.08711166, 1.26443741,
       1.56896428, 1.42226149, 1.71174795, 1.72149378, 1.22695841,
       1.17629264, 1.02925519, 1.17393359, 1.01233178, 1.17701202,
       1.26888831, 1.21975251, 1.80580698, 1.22872837, 1.03124048,
       1.37208174, 1.26351299, 1.        , 1.00130014, 1.00099319,
       1.03406233, 1.01079854, 1.01589366, 1.1511331 , 1.0481572 ,
       1.        , 1.01891369, 1.04559279, 1.13912974, 1.02386319,
       1.01009894, 1.        , 1.        , 1.10758456, 1.051198  ,
       1.62280372, 1.10928011, 1.01408145, 1.11733322, 1.02306813,
       1.00594113, 1.01383628, 1.04016588, 1.00546389, 1.00296978,
       1.1231047 , 1.0350133 , 1.        , 1.00757676, 1.02090408,
       1.00405543, 1.0252188 , 1.01962772, 1.        , 1.00493109,
       1.        , 1.01827676, 1.00401758, 1.01179667, 1.24546089,
       1.71649302, 1.08595734, 1.01928052, 1.05378886, 1.0817296 ,
       1.0223457 , 1.00392739, 1.00787732, 1.06560713, 1.02458

In [43]:
num_features=X.shape[1]

In [44]:
num_features

96

In [45]:
feature_indices=np.arange(num_features) #0 to 95

In [46]:
feature_indices

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95])

In [47]:
feature_names=list(X.columns)

In [49]:
# Performing feature selection using LDA by using the absolute values of the
# LDA coefficients as a measure of feature importance.

In [74]:
df_feature_score=pd.DataFrame({"Feature_names":feature_names,"feature_scores":lda_coefficients})
df_feature_score

Feature_names  feature_scores
0                     time_left        1.140514
1                      ct_score        1.023482
2                       t_score        1.023610
3                           map        1.087112
4                  bomb_planted        1.264437
..                          ...             ...
91  t_grenade_incendiarygrenade        1.010063
92    ct_grenade_molotovgrenade        1.008522
93     t_grenade_molotovgrenade        1.104241
94      ct_grenade_decoygrenade        1.002317
95       t_grenade_decoygrenade        1.032932

[96 rows x 2 columns]

In [75]:
top_20_values=df_feature_score.nlargest(20,'feature_scores')
top_20_values

Feature_names  feature_scores
17           t_weapon_ak47        1.805807
8                  t_armor        1.721494
65          t_weapon_sg553        1.716493
7                 ct_armor        1.711748
40          ct_weapon_m4a4        1.622804
5                ct_health        1.568964
6                 t_health        1.422261
20           ct_weapon_awp        1.372082
15         t_players_alive        1.268888
4             bomb_planted        1.264437
89  t_grenade_smokegrenade        1.263718
21            t_weapon_awp        1.263513
64         ct_weapon_sg553        1.245461
18           ct_weapon_aug        1.228728
9                 ct_money        1.226958
16          ct_weapon_ak47        1.219753
87     t_grenade_flashbang        1.217213
14        ct_players_alive        1.177012
10                 t_money        1.176293
12               t_helmets        1.173934

In [52]:
# Selecting the top 20 features based on the feature importance

In [53]:
top_20_values.head(20)

Feature_names  feature_scores
17           t_weapon_ak47        1.805807
8                  t_armor        1.721494
65          t_weapon_sg553        1.716493
7                 ct_armor        1.711748
40          ct_weapon_m4a4        1.622804
5                ct_health        1.568964
6                 t_health        1.422261
20           ct_weapon_awp        1.372082
15         t_players_alive        1.268888
4             bomb_planted        1.264437
89  t_grenade_smokegrenade        1.263718
21            t_weapon_awp        1.263513
64         ct_weapon_sg553        1.245461
18           ct_weapon_aug        1.228728
9                 ct_money        1.226958
16          ct_weapon_ak47        1.219753
87     t_grenade_flashbang        1.217213
14        ct_players_alive        1.177012
10                 t_money        1.176293
12               t_helmets        1.173934

In [54]:
top_20_values.index

Int64Index([17, 8, 65, 7, 40, 5, 6, 20, 15, 4, 89, 21, 64, 18, 9, 16, 87, 14,
            10, 12],
           dtype='int64')

In [55]:
x_train=x_train[:,[17, 8, 65, 7, 40, 5, 6, 20, 15, 4, 89, 21, 64, 18, 9, 16, 87, 14,
            10, 12]]

In [56]:
x_test=x_test[:,[17, 8, 65, 7, 40, 5, 6, 20, 15, 4, 89, 21, 64, 18, 9, 16, 87, 14,
            10, 12]]

In [57]:
# Logistic Regression
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr.fit(x_train,y_train)
y_pred=lr.predict(x_test)

C:\Users\Dell\anaconda3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [58]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.7516951229474717

In [59]:
from sklearn.metrics import *

In [60]:
print(confusion_matrix(y_test,y_pred))

[[9167 2837]
 [3242 9236]]


In [61]:
# Decision Tree
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier()
dtc.fit(x_train,y_train)
y_pred=dtc.predict(x_test)

In [62]:
accuracy_score(y_test,y_pred)

0.8157830242627236

In [63]:
# Random Forest
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier()
rfc.fit(x_train,y_train)
y_pred=rfc.predict(x_test)

C:\Users\Dell\AppData\Local\Temp\ipykernel_9556\2310176018.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  rfc.fit(x_train,y_train)


In [64]:
accuracy_score(y_test,y_pred)

0.855567355608202

In [ ]:
# KNN

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knc= KNeighborsClassifier()
knc.fit(x_train,y_train)
y_pred=knc.predict(x_test)

/usr/local/lib/python3.10/dist-packages/sklearn/neighbors/_classification.py:215: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


In [ ]:
accuracy_score(y_test,y_pred)

0.7880892083980067

In [ ]:
# Clearly we can see that random forest is the best model for this dataset.
# It has the highest accuracy